[package]
name = "curly-goggles"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.16"
mio = "0.6.19"
sodiumoxide = "0.2.2"
rand = "0.6.5"
